RailsApplication1/config/routes.rb
RailsApplication1::Application.routes.draw do
  resources :notes
  root :to => "notes#index"

end

RailsApplication1/app/models/note.rb
class Note < ActiveRecord::Base
end

RailsApplication1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RailsApplication1/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :prepare_note, :only => [:show, :edit, :update, :destroy]
  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new params[:note]
    if @note.save
      redirect_to note_path(@note)
    else
      flash.now[:error] = "Error: #{@note.errors.full_messages.join('<br />')}"
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @note.update_attributes params[:note]
      redirect_to note_path(@note)
    else
      flash.now[:error] = "Error: #{@note.errors.full_messages.join('<br />')}"
      render :action => "edit"
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path
  end

private

  def prepare_note
    @note = Note.find params[:id]
  end
end

RailsApplication1/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsApplication1/app/helpers/notes_helper.rb
module NotesHelper
end

RailsApplication1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApplication1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

RailsApplication1/app/views/notes/_form.html.erb
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>
<div>
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>
<div>
  <%= form.submit "Submit" %>
</div>

RailsApplication1/app/views/notes/edit.html.erb
<%= form_for @note do |f| %>
  <%= render :partial => "form", :object => f %>
<% end %>

RailsApplication1/app/views/notes/index.html.erb
<ul>
<% @notes.each do |note| %>
  <li><%= link_to note.title, note %></li>
<% end -%>
</ul>
<% if @notes.empty? %>
  No notes exist
<% end -%>

<%= link_to "Add new note", new_note_path %>

RailsApplication1/app/views/notes/new.html.erb
<%= form_for @note do |f| %>
  <%= render :partial => "form", :object => f %>
<% end %>

RailsApplication1/app/views/notes/show.html.erb
<div>
  Title:
  <%= @note.title %>
</div>
<div>
  Content:
  <%= @note.content %>
</div>
<div>
  <%= link_to "Edit", edit_note_path(@note) %>
  <%= link_to "Delete", note_path(@note), :method => :delete %>
</div>