WriteBoard/config/routes.rb
WriteBoard::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :messages do
    resources :replies, :shallow => true
  end
  root :to => "messages#index"

end

WriteBoard/app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :author

  belongs_to :author, :class_name => "User"
  belongs_to :parent, :class_name => "Message"

  has_many :replies, :class_name => "Message", :foreign_key => "parent_id", :dependent => :destroy

  validates :author, :presence => true # this will have no effect in cucumber test but needed in unit test
  validates :content, :length => {:in => 3..150}
end

WriteBoard/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable

  has_many :messages, :foreign_key => "author_id", :dependent => :destroy

  attr_accessible :email, :password, :password_confirmation

  def update_with_password(params={})
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
      result = update_without_password(params)
    else
      result = if valid_password?(current_password)
        update_attributes(params)
      else
        self.attributes = params
        self.valid?
        self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
        false
      end
    end

    clean_up_passwords
    result
  end
end

WriteBoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

WriteBoard/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  before_filter :prepare_messages, :only => [:index]
  before_filter :prepare_message, :only => [:edit, :update, :destroy]

  def index

  end

  def create
    @message = current_user.messages.new(params[:message])
    if @message.save
      flash[:notice] = "Message posted successfully."
      redirect_to "index"
    else
      prepare_messages
      render "index"
    end
  end

  def edit
    
  end

  def update
    if @message.update_attributes params[:message]
      flash[:notice] = "Message updated successfully."
      redirect_to "index"
    else
      render "edit"
    end
  end

  def destroy
    @message.destroy
    flash[:notice] = "Message deleted successfully."
    redirect_to "index"
  end

private

  def prepare_messages
    @messages = Message.all
  end

  def prepare_message
    @message = Message.find params[:id]
  end
end

WriteBoard/app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :prepare_message, :only => [:new, :create]
  before_filter :prepare_reply, :only => [:edit, :update, :destroy]

  def new
    @reply = @message.replies.new :author => current_user
  end

  def create
    @reply = @message.replies.new params[:message].merge(:author => current_user)
    if @reply.save
      flash[:notice] = "Message replied successfully."
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if @reply.update_attributes params[:message]
      flash[:notice] = "Reply updated successfully."
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @reply.destroy
    flash[:notice] = "Reply deleted successfully."
    redirect_to root_path
  end

private

  def prepare_message
    @message = Message.find params[:message_id]
  end

  def prepare_reply
    @reply = Message.find params[:id]
  end
end

WriteBoard/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_user_session_path
  end
end

WriteBoard/app/helpers/application_helper.rb
module ApplicationHelper
end

WriteBoard/app/helpers/messages_helper.rb
module MessagesHelper
end

WriteBoard/app/helpers/replies_helper.rb
module RepliesHelper
end

WriteBoard/app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

WriteBoard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WriteBoard</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div>
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%>
  </div>
  <div>
    <%= yield %>
  </div>
</body>
</html>

WriteBoard/app/views/messages/_message.html.erb
<div id="<%= "message_#{message.id}" %>">
  <div>
    Author: <%= message.author.email %>
  </div>
  <% if message.author == current_user %>
    <div>
      <%= link_to "Edit", edit_message_path(message) %>
      <%= link_to "Delete", message, :method => :delete %>
    </div>
  <% end -%>
  <div>
    <%= message.content %>
  </div>
  <div>
    <div>
      <%= link_to "Reply", new_message_reply_path(message) if user_signed_in? %>
    </div>
    <div id="<%= "message_#{message.id}" %>_replies_container">
      <%= render :partial => "/replies/reply", :collection => message.replies, :locals => {:message => message} %>
    </div>
  </div>
</div>

WriteBoard/app/views/messages/edit.html.erb
<%= form_for @message do |f| %>
  <%= f.error_messages %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "Update" %>
  </div>
<% end %>

WriteBoard/app/views/messages/index.html.erb
<div>
  <% if user_signed_in? %>
    <%= link_to "Edit Profile", edit_user_registration_path %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end -%>
</div>

<% if user_signed_in? %>
<div>
  <%= form_for Message.new do |f| %>
    <%= f.error_messages %>
    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
    <div>
      <%= f.submit "Post" %>
    </div>
  <% end %>
</div>
<% end -%>

<div id="messages_container">
  <%= render @messages %>
</div>

WriteBoard/app/views/replies/_reply.html.erb
<div id="<%= "message_#{reply.id}" %>">
  <div>
    Reply by: <%= reply.author.email %>
  </div>
  <% if reply.author == current_user %>
    <div>
      <%= link_to "Edit", edit_reply_path(reply) %>
      <%= link_to "Delete", reply_path(reply), :method => :delete %>
    </div>
  <% end -%>
  <div>
    <%= reply.content %>
  </div>
  <div>
    <div>
      <%= link_to "Reply", new_message_reply_path(reply) if user_signed_in? %>
    </div>
    <div id="<%= "message_#{reply.id}" %>_replies_container">
      <%= render :partial => "/replies/reply", :collection => reply.replies %>
    </div>
  </div>
</div>

WriteBoard/app/views/replies/edit.html.erb
<%= form_for @reply, :url => reply_path(@reply) do |f| %>
  <%= f.error_messages %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "Update" %>
  </div>
<% end %>

WriteBoard/app/views/replies/new.html.erb
<%= form_for @reply, :url => message_replies_path(@message) do |f| %>
  <%= f.error_messages %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit "Reply" %>
  </div>
<% end %>

WriteBoard/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>